In [130]:
import requests
import pandas as pd
import csv
import pycountry

In [131]:
API_KEY = '92223e2767b50cde8ee665fe885b0021'

In [132]:
def geocode_address(city):
    # Form the API request URL
    url = f'http://api.openweathermap.org/geo/1.0/direct?q={city}&limit=5&appid=bd5e378503939ddaee76f12ad7a97608'
    response = requests.get(url)
    
    # Check if the request was successful
    if response.status_code == 200:
        data = response.json()
        # Extract relevant information
        result = data[0]
        lat = result['lat']
        lon = result['lon']
        ct_code = result['country']
        country = country = pycountry.countries.get(alpha_2 = ct_code).name
        return [city, lat, lon, ct_code, country] 
            # Return the details
    else:
        return {'error': f'Request failed with status code {response.status_code}'}

In [133]:
csv_file_path = 'countries.csv'

# Open the file in write mode
with open(csv_file_path, mode='w', newline='', encoding = "utf-16") as file:
    writer = csv.writer(file)
    cities = ['London', 'Paris', 'Madrid', 'Berlin', 'Warsaw', 'Bern', 'Brussels', 'Dublin', 'Moscow', 'Rome', 'Ankara',
              'Budapest', 'Sofia', 'Amsterdam', 'Oslo', 'Stockholm', 'Helsinki', 'Copenhagen', 'Tallinn', 'Vienna', 'Zagreb',
              'Lisbon', 'Kyiv', 'Athens', 'Prague', 'Tirana', 'Bucharest', 'Belgrade', 'Podgorica', 'Nicosia', 'Ljubljana', 'Luxembourg',
                'Reykjavik', 'Bratislava', 'Minsk','Sarajevo', 'Vilnius', 'Chișinău', 'Riga', 'Skopje', 
                'Vaduz', 'Tbilisi', 'Yerevan', 'Baku', 'Monaco', 'San Marino', 'Tórshavn', 'Andorra la Vella', 'Gibraltar']
    writer.writerow(['city','lat','lon','ct_code', 'country'])
    for city in cities:
        writer.writerow(map(str, geocode_address(city)))

In [134]:
pd.read_csv('countries.csv', encoding = "utf-16")

                city        lat        lon ct_code                 country
0             London  51.507322  -0.127647      GB          United Kingdom
1              Paris  48.858890   2.320041      FR                  France
2             Madrid  40.416705  -3.703582      ES                   Spain
3             Berlin  52.517037  13.388860      DE                 Germany
4             Warsaw  52.231958  21.006725      PL                  Poland
5               Bern  46.948271   7.451451      CH             Switzerland
6           Brussels  50.846557   4.351697      BE                 Belgium
7             Dublin  53.349801  -6.260296      IE                 Ireland
8             Moscow  55.750446  37.617494      RU      Russian Federation
9               Rome  41.893320  12.482932      IT                   Italy
10            Ankara  39.920789  32.854048      TR                 Türkiye
11          Budapest  47.497994  19.040359      HU                 Hungary
12             Sofia  42.697703  23.321736      BG                Bulgaria
13         Amsterdam  52.372760   4.893604      NL             Netherlands
14              Oslo  59.913330  10.738970      NO                  Norway
15         Stockholm  59.325117  18.071093      SE                  Sweden
16          Helsinki  60.167488  24.942747      FI                 Finland
17        Copenhagen  55.686724  12.570072      DK                 Denmark
18           Tallinn  59.437216  24.745369      EE                 Estonia
19            Vienna  48.208354  16.372504      AT                 Austria
20            Zagreb  45.842641  15.962231      HR                 Croatia
21            Lisbon  38.707751  -9.136592      PT                Portugal
22              Kyiv  50.450034  30.524136      UA                 Ukraine
23            Athens  37.983941  23.728305      GR                  Greece
24            Prague  50.087465  14.421254      CZ                 Czechia
25            Tirana  41.330514  19.825563      AL                 Albania
26         Bucharest  44.436141  26.102720      RO                 Romania
27          Belgrade  44.817813  20.456897      RS                  Serbia
28         Podgorica  42.441524  19.262108      ME              Montenegro
29           Nicosia  35.174898  33.363857      CY                  Cyprus
30         Ljubljana  46.050027  14.506929      SI                Slovenia
31        Luxembourg  49.611277   6.129799      LU              Luxembourg
32         Reykjavik  64.145981 -21.942237      IS                 Iceland
33        Bratislava  48.143515  17.108279      SK                Slovakia
34             Minsk  53.902472  27.561823      BY                 Belarus
35          Sarajevo  43.851977  18.386687      BA  Bosnia and Herzegovina
36           Vilnius  54.687046  25.282911      LT               Lithuania
37          Chișinău  47.024512  28.832292      MD    Moldova, Republic of
38              Riga  56.949398  24.105185      LV                  Latvia
39            Skopje  41.996092  21.431649      MK         North Macedonia
40             Vaduz  47.139286   9.522796      LI           Liechtenstein
41           Tbilisi  41.693459  44.801449      GE                 Georgia
42           Yerevan  40.177625  44.512617      AM                 Armenia
43              Baku  40.375588  49.832801      AZ              Azerbaijan
44            Monaco  43.731142   7.419758      MC                  Monaco
45        San Marino  43.936400  12.446699      SM              San Marino
46          Tórshavn  62.012000  -6.768000      FO           Faroe Islands
47  Andorra la Vella  42.506939   1.521247      AD                 Andorra
48         Gibraltar  36.140807  -5.354129      GI               Gibraltar